# Generated by Django 5.1 on 2025-01-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0024_order_delivery_date_order_payment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickFromHome',
        ),
    ]
