# Generated by Django 5.1 on 2025-01-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0025_delete_pickfromhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickFromHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.billing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.tbl_user')),
            ],
        ),
    ]
