# Generated by Django 5.1 on 2025-01-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0026_pickfromhome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickfromhome',
            old_name='billing_address',
            new_name='billing',
        ),
    ]
