# Generated by Django 5.1 on 2025-01-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0027_rename_billing_address_pickfromhome_billing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickFromHome',
        ),
    ]
