# Generated by Django 5.1 on 2025-01-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0034_storevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
