# Generated by Django 5.1 on 2025-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0035_order_out_for_delivery_date_order_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_staff',
            name='role',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Delivery', 'Delivery'), ('Try at home', 'Try at home')], max_length=50),
        ),
    ]
