# Generated by Django 5.1 on 2025-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0037_remove_booking_is_active_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
