# Generated by Django 5.1 on 2025-01-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0040_newproductrequest_restockrequest_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('documents', models.FileField(upload_to='vendor_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.tbl_login')),
            ],
        ),
    ]
