# Generated by Django 5.1 on 2025-01-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0041_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='metaltype',
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='supplier_products/')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.category')),
                ('metaltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.metaltype')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
