# Generated by Django 5.1 on 2025-01-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0043_delete_restockrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.vendorproduct')),
            ],
        ),
    ]
