# Generated by Django 5.1 on 2025-02-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0046_remove_restockrequest_vendor_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='vendor_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.category')),
                ('metaltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.metaltype')),
                ('stonetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.stonetype')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Product',
                'verbose_name_plural': 'Vendor Products',
            },
        ),
    ]
