# Generated by Django 5.1 on 2025-02-01 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0047_vendorproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.CharField(max_length=255)),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='jewelryapp.vendorproduct')),
            ],
            options={
                'verbose_name': 'Vendor Product Attribute',
                'verbose_name_plural': 'Vendor Product Attributes',
            },
        ),
    ]
