# Generated by Django 5.1 on 2025-02-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0051_paymentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorpayment',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='payment_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('post', 'Post')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
