# Generated by Django 5.1 on 2025-02-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0052_rename_created_at_vendorpayment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
    ]
