# Generated by Django 5.1 on 2025-02-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0053_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bis_hallmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='making_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
