# Generated by Django 5.1 on 2025-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0058_vendorproductstone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproductstone',
            name='vendor_product',
        ),
        migrations.RemoveField(
            model_name='vendorproductattribute',
            name='vendor_product',
        ),
        migrations.RemoveField(
            model_name='vendorproductstone',
            name='stone_type',
        ),
        migrations.AlterField(
            model_name='stonetype',
            name='name',
            field=models.CharField(choices=[('diamond', 'Diamond'), ('ruby', 'Ruby'), ('sapphire', 'Sapphire'), ('emerald', 'Emerald')], max_length=50),
        ),
        migrations.DeleteModel(
            name='VendorProduct',
        ),
        migrations.DeleteModel(
            name='VendorProductAttribute',
        ),
        migrations.DeleteModel(
            name='VendorProductStone',
        ),
    ]
