# Generated by Django 5.1 on 2025-02-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0059_remove_vendorproductstone_vendor_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity_value', models.CharField(max_length=10)),
                ('purity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=100)),
                ('metal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.metaltype')),
            ],
            options={
                'unique_together': {('metal_type', 'purity_value')},
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('vendor_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Kids', 'Kids'), ('Baby', 'Baby')], default='Unisex', max_length=6)),
                ('main_image', models.ImageField(upload_to='vendor_products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vendor_products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vendor_products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vendor_products/')),
                ('product_video', models.FileField(blank=True, null=True, upload_to='vendor_product_videos/')),
                ('home_delivery', models.BooleanField(default=False)),
                ('store_pickup', models.BooleanField(default=False)),
                ('try_at_home', models.BooleanField(default=False)),
                ('estimated_delivery', models.PositiveIntegerField(default=7)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('bis_hallmark', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='jewelryapp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.metaltype')),
                ('purity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.metalpurity')),
                ('vendor_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metal_details', to='jewelryapp.vendorproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stone_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('making_charges_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('making_charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_details', to='jewelryapp.vendorproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7)),
                ('count', models.PositiveIntegerField()),
                ('quality', models.CharField(max_length=50)),
                ('rate_per_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.stonetype')),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='jewelryapp.vendorproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('datatype', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='string', max_length=50)),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='jewelryapp.vendorproduct')),
            ],
            options={
                'unique_together': {('vendor_product', 'attribute_name')},
            },
        ),
    ]
