# Generated by Django 5.1 on 2025-03-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0060_metalpurity_vendorproduct_vendorproductmetal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproduct',
            name='bis_hallmark',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='home_delivery',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='product_video',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='store_pickup',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='try_at_home',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='weight',
        ),
        migrations.CreateModel(
            name='VendorAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField()),
                ('bis_hallmark', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_delivery', models.PositiveIntegerField(default=7)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Kids', 'Kids'), ('Baby', 'Baby')], default='Unisex', max_length=6)),
                ('home_delivery', models.BooleanField(default=False)),
                ('store_pickup', models.BooleanField(default=False)),
                ('try_at_home', models.BooleanField(default=False)),
                ('vendor_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_details', to='jewelryapp.vendorproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='vendor_products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vendor_products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vendor_products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vendor_products/')),
                ('product_video', models.FileField(blank=True, null=True, upload_to='vendor_product_videos/')),
                ('vendor_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jewelryapp.vendorproduct')),
            ],
        ),
    ]
