# Generated by Django 5.1 on 2025-03-01 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0061_remove_vendorproduct_bis_hallmark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StonePurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity_grade', models.CharField(max_length=20)),
                ('clarity_rating', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.stonetype')),
            ],
            options={
                'verbose_name_plural': 'Stone Purities',
                'unique_together': {('stone_type', 'purity_grade')},
            },
        ),
    ]
