# Generated by Django 5.1 on 2025-03-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0063_vendorpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
