# Generated by Django 5.1 on 2025-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0065_datechangerequest_delete_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpurchase',
            name='payment_processed',
            field=models.BooleanField(default=False),
        ),
    ]
